version: '3'
services:
  backend:
    build:
      context: ./backend
    container_name: mjob_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mjob_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

