version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: mjob_backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/yourdbname
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mjob_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
  
