version: '3'
services:
  backend:
    build:
      context: ./backend
    container_name: backend_jenkins
    ports:
      - "5001:5000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_jenkins
    ports:
      - "3001:80"
    depends_on:
      - backend

