version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo_jenkins
    ports:
      - "27018:27017"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_jenkins
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
